routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// AUTH ROUTES
Route::prefix('/auth')->name('auth.')->group(function ()
{
    $auth = "AuthController";

    Route::get('/logout', "$auth@logout")->name('logout')->middleware('auth');

    Route::post('/login', "$auth@login")->name('login');
});

// GUIDE ROUTES
Route::prefix('/guide')->name('guide.')->group(function ()
{
    $guide = "GuideController";

    Route::get('/', "$guide@home")->name('home');
    Route::get('/server-rules', "$guide@server_rules")->name('server-rules');
});

// HELPERS ROUTES
Route::prefix('/helpers')->name('helpers.')->group(function ()
{
    $helpers = 'HelpersController';

    Route::get('/profile/activation/{type?}', "$helpers@profile_activation")->name('profile.activation');

    Route::get('/profile/delete/{type?}', "$helpers@profile_delete")->name('profile.delete');

    Route::get('/email/activation', "$helpers@email_activation")->name('email.activation');

    Route::get('/reset-password', "$helpers@reset_password")->name('reset.password');
    Route::get('/reset-password/expire', "$helpers@reset_password_expire")->name('reset.password.expire');
    Route::get('/reset-password/end', "$helpers@reset_password_end")->name('reset.password.end');
});

// MAIN ROUTES
$main = "MainController";

Route::get('/', "$main@home")->name('home');
Route::get('/mentions-legales', "$main@mentions")->name('mentions');
Route::get('/download', "$main@download")->name('download');

Route::post('/contact/send', "$main@contact")->name('contact');

// USER ROUTES
Route::prefix('/user')->name('user.')->group(function ()
{
    $user = "UserController";

    Route::get('/profile/activation/{token}', "$user@activation")->name('activation');
    Route::get('/password-reset', "$user@password_reset")->name('reset.password.view');
    Route::get('/password-reset/{token}', "$user@password_reset_end")->name('reset.password.end');

    Route::post('/profile/inscription', "$user@inscription")->name('inscription');
    Route::post('/password-reset/send', "$user@password_reset")->name('reset.password');

    Route::put('/profile/update', "$user@update")->name('update');
    Route::put('/password/update', "$user@password_reset")->name('reset.password.update');

    Route::match(['get', 'delete'], '/profile/delete/{token?}', "$user@delete")->name('delete');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public static function findWithEmail(string $email)
    {
        return self::where('email', $email)->first();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Notifications\DeleteAccount;
use App\Notifications\EmailActivation;
use App\Notifications\ResetPassword;
use App\Notifications\Support;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

/**
 * Use to control the user profile
 * Class UserController
 * @package App\Http\Controllers
 */

class UserController extends Controller
{
    /**
     * Use to control the address email verification
     * @param $token
     * @return \Illuminate\Http\RedirectResponse|void
     */
    public function activation($token)
    {
        // Decode the verification token
        $token = json_decode(decrypt($token));

        // Get the user in the database
        $user = User::findWithEmail($token->email);

        // If the user is'nt found in the database, make a HTTP error 500
        if ($user === null)
            return abort(500);

        if ($token->time >= time()) {
            // If the token is'nt expire
            // Update the email verification field in the database
            $user->email_verified_at = now();
            $user->save();
            // Redirect to the profile activation page in HelpersController
            return redirect()->route('helpers.profile.activation');
        } else {
            // If the token is expire
            // Remake a new token
            $token = $this->gen_user_token($user->email);
            // Send an other activation email
            $user->notify(new EmailActivation($token));
            // Send to the profile activation page in HelpersController with the expire type
            return redirect()->route('helpers.profile.activation', ['type' => 'expire']);
        }
    }

    /**
     * Use to delete profile
     * @param Request $request
     * @param null $token
     * @return \Illuminate\Http\RedirectResponse|void
     */
    public function delete(Request $request, $token = null)
    {
        if ($request->isMethod('delete')) {
            // If delete request method is used
            // Test the $_POST variable
            $request->validate([
                'user' => ['required', 'string']
            ]);

            // Get the user in the database
            $user = User::find(decrypt($request->input('user')));
            // Generate a token with the user's email
            $token = $this->gen_user_token($user->email);
            // Send the delete profile confirmation email to the user
            $user->notify(new DeleteAccount($token));
            // Redirect to the delete profile page in HelpersController
            return redirect()->route('helpers.profile.delete');
        } elseif ($request->isMethod('get') && $token !== null) {
            // If get request method is used
            // Decode the token
            $token = json_decode(decrypt($token));
            // Get a user in the database with his email
            $user = User::findWithEmail($token->email);

            if ($user === null)
                return abort(500);

            if ($token->time >= time()) {
                $user->delete();
                return redirect()->route('helpers.profile.delete', ['type' => 'end']);
            } else
                return redirect()->route('helpers.profile.delete', ['type' => 'expire']);
        } else
            return abort(500);
    }

    public function inscription(Request $request)
    {
        $validate = Validator::make($request->all(), [
            'email' => ['required', 'email', 'unique:users,email'],
            'username' => ['required', 'unique:users,username', 'alpha_num'],
            'password' => ['required', 'min:8', 'same:confPassword'],
            'birthday' => ['required', 'date']
        ]);

        $validate->validate();

        $current_time = now();
        $major_date = new \DateTime($current_time->year - 18 . '-' . $current_time->month . '-' . $current_time->day);

        if ($request->input('birthday') > $major_date)
            return response(json_encode([
                'erros' => "Vous devez avoir au moins 18 pour vous inscrire"
            ]), 403);
        else {
            $user = new User();

            $user->email = $request->input('email');
            $user->username = strtolower($request->input('username'));
            $user->birthday = $request->input('birthday');
            $user->password = Hash::make($request->input('password'));

            $user->save();

            $token = $this->gen_user_token($user->email);
            $user->notify(new EmailActivation($token));

            return response()->json([
                'success' => route('helpers.email.activation')
            ]);
        }
    }

    public function password_reset(Request $request)
    {
        if ($request->isMethod('get'))
            return view('user.password-reset');
        elseif ($request->isMethod('put')) {
            $request->validate([
                'user' => ['required', 'string'],
                'password' => ['required', 'min:8', 'same:confPassword']
            ]);

            $user = User::find(decrypt($request->input('user')));

            $user->password = Hash::make($request->input('password'));
            $user->save();

            $user->notify(new Support('reset-end'));

            return redirect()->route('helpers.reset.password.end');
        } else if ($request->isMethod('post')) {
            $request->validate([
                'userEmail' => ['required', 'email']
            ]);

            $user = User::findWithEmail($request->input('userEmail'));

            if ($user === null)
                return redirect()->route('user.reset.password.view')->with('error', "Ce compte n'existe pas.");

            $token = $this->gen_user_token($user->email);
            $user->notify(new ResetPassword($token));

            return redirect()->route('helpers.reset.password');
        } else
            return abort(500);
    }

    public function password_reset_end(string $token)
    {
        $token = json_decode(decrypt($token));
        $user = User::findWithEmail($token->email);

        if ($user === null)
            return abort(500);

        if ($token->time >= time()) {
            return view('user.password-reset-form', ['user' => encrypt($user->id)]);
        } else {
            return redirect()->route('helpers.reset.password.expire');
        }
    }

    public function update(Request $request)
    {
        Validator::make($request->only('user'), [
            'user' => ['required', 'string']
        ]);

        $user = User::findWithEmail(decrypt($request->input('user')));

        if ($user->email !== $request->input('email')) {
            $request->validate([
                'email' => ['required', 'email', 'unique:users,email']
            ]);
            $user->email = $request->input('email');
        }
        if ($user->username !== $request->input('username')) {
            $request->validate([
                'username' => ['required', 'alpha_num', 'unique:users,username']
            ]);
            $user->username = strtolower($request->input('username'));
        }
        if ($user->birthday !== $request->input('birthday')) {
            $request->validate([
                'birthday' => ['required', 'date']
            ]);
            $user->birthday = $request->input('birthday');
        }
        if (!empty($request->input('password'))) {
            $request->validate([
                'password' => ['required', 'min:8', 'same:confPassword']
            ]);
            $user->password = Hash::make($request->input('password'));
        }

        $user->save();

        return response()->json([
            'success' => "hello"
        ]);
    }
}

resources/views/user/password-reset-form.blade.php
@extends('layouts.main')

@section('title', "Réinitialiser votre mot de passe !")

@section('script')
    <script src="{{ asset('js/dist/password-form.js') }}"></script>
 @endsection

@section('main')
    <section class="row">
            <div class="col bg-white p-3">
                <h1>Réinitialiser votre mot de passe maintenant.</h1>
                <hr>
                @if ($errors->any())
                    <div role="alert" class="alert alert-warning">
                        <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                        </ul>
                    </div>
                @endif
                <form id="passwordForm" action="{{ route('user.reset.password.update') }}" method="post"
                      style="max-width: 400px; margin: 0 auto;">
                    @csrf
                    @method('put')
                    <input type="hidden" name="user" value="{{ $user }}">
                    <fieldset class="form-group">
                        <label for="password">Mot de passe</label>
                        <input type="password" class="form-control" name="password" id="password" aria-describedby="passwordText">
                        <small id="passwordText" class="form-text text-muted">
                            Le mot de passe doit au moins contenir 8 caractères.
                        </small>
                    </fieldset>
                    <fieldset class="form-group">
                        <label for="confPassword">Confirmation du mot de passe</label>
                        <input type="password" class="form-control" name="confPassword" id="confPassword">
                        <div id="passwordControllerBis">
                            <span id="low"></span>
                            <span id="medium"></span>
                            <span id="strong"></span>
                            <p></p>
                        </div>
                    </fieldset>
                    <fieldset class="form-group text-right">
                        <button type="submit" class="btn btn-primary btn-sm">Réinitialiser votre mot de passe</button>
                    </fieldset>
                </form>
            </div>
    </section>
@endsection

resources/views/user/password-reset.blade.php
@extends('layouts.main')

@section('title', "Réinitialisez votre mot de passe")

@section('script')
    <script>
        window.scrollTo(0, 150);
    </script>
@endsection

@section('main')
    <section class="row">
        <div class="col bg-white p-3">
            <h1>Réinitialisez votre mot de passe.</h1>
            <p>Entrez l'adresse e-mail lié à votre compte afin de réinitialiser votre mot de passe.</p>
            @if (session('error'))
                <p class="text-danger">{{ session('error') }}</p>
            @endif
            <form action="{{ route('user.reset.password') }}" method="post" class="row" style="max-width: 500px;">
                @csrf
                <fieldset class="form-group col-12 col-md-9">
                    <input type="email" name="userEmail" id="userEmail" placeholder="mon-email@exemple.fr" class="form-control" required>
                </fieldset>
                <fieldset class="form-group text-right col-12 col-md-3">
                    <button type="submit" class="btn btn-secondary">Envoyer</button>
                </fieldset>
            </form>
        </div>
    </section>

@endsection