routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// AUTH ROUTES
Route::prefix('/auth')->name('auth.')->group(function ()
{
    $auth = "AuthController";

    Route::get('/logout', "$auth@logout")->name('logout')->middleware('auth');

    Route::post('/login', "$auth@login")->name('login');
});

// GUIDE ROUTES
Route::prefix('/guide')->name('guide.')->group(function ()
{
    $guide = "GuideController";

    Route::get('/', "$guide@home")->name('home');
    Route::get('/server-rules', "$guide@server_rules")->name('server-rules');
});

// HELPERS ROUTES
Route::prefix('/helpers')->name('helpers.')->group(function ()
{
    $helpers = 'HelpersController';

    Route::get('/profile/activation/{type?}', "$helpers@profile_activation")->name('profile.activation');

    Route::get('/profile/delete/{type?}', "$helpers@profile_delete")->name('profile.delete');

    Route::get('/email/activation', "$helpers@email_activation")->name('email.activation');

    Route::get('/reset-password', "$helpers@reset_password")->name('reset.password');
    Route::get('/reset-password/expire', "$helpers@reset_password_expire")->name('reset.password.expire');
    Route::get('/reset-password/end', "$helpers@reset_password_end")->name('reset.password.end');
});

// MAIN ROUTES
$main = "MainController";

Route::get('/', "$main@home")->name('home');
Route::get('/mentions-legales', "$main@mentions")->name('mentions');
Route::get('/download', "$main@download")->name('download');

Route::post('/contact/send', "$main@contact")->name('contact');

// USER ROUTES
Route::prefix('/user')->name('user.')->group(function ()
{
    $user = "UserController";

    Route::get('/profile/activation/{token}', "$user@activation")->name('activation');
    Route::get('/password-reset', "$user@password_reset")->name('reset.password.view');
    Route::get('/password-reset/{token}', "$user@password_reset_end")->name('reset.password.end');

    Route::post('/profile/inscription', "$user@inscription")->name('inscription');
    Route::post('/password-reset/send', "$user@password_reset")->name('reset.password');

    Route::put('/profile/update', "$user@update")->name('update');
    Route::put('/password/update', "$user@password_reset")->name('reset.password.update');

    Route::match(['get', 'delete'], '/profile/delete/{token?}', "$user@delete")->name('delete');
});

resources/views/modals/contact-modal.blade.php
<div class="modal fade" id="contactModal" tabindex="-1" role="dialog" aria-labelledby="contactModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Nous contacter</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body p-3">
                <form id="contactForm" action="{{ route('contact') }}" method="post">
                    @csrf
                    <fieldset class="form-group">
                        <label for="contactEmail">Votre adresse e-mail</label>
                        <input type="email" class="form-control" name="contactEmail" id="contactEmail"
                               placeholder="mon-email@exemple.fr">
                    </fieldset>
                    <fieldset class="form-group">
                        <label for="contactSubject">Sujet du message</label>
                        <input type="text" class="form-control" name="contactSubject" id="contactSubject">
                    </fieldset>
                    <fieldset class="form-group">
                        <label for="contactMessage">Votre message</label>
                        <textarea class="form-control" name="contactMessage" id="contactMessage" rows="8"></textarea>
                    </fieldset>
                    <fieldset class="form-group text-center">
                        <button type="submit" class="btn btn-success btn-block">Envoyer</button>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/modals/inscript-modal.blade.php
<div class="modal fade" id="inscriptModal" tabindex="-1" role="dialog" aria-labelledby="inscriptModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Inscription</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body p-3">
                <p class="text-danger small text-right">
                    * Champs obligatoires
                </p>
                <form id="inscriptForm" action="{{ route('user.inscription') }}" method="post">
                    @csrf
                    <fieldset class="form-group">
                        <label for="username">Pseudo Mincraft <span class="text-danger">*</span></label>
                        <input type="text" class="form-control" name="username" id="username" placeholder="pseudo1234">
                    </fieldset>
                    <fieldset class="form-group">
                        <label for="email">Adresse e-mail <span class="text-danger">*</span></label>
                        <input type="email" class="form-control" name="email" id="email" placeholder="mon-email@exemple.fr">
                    </fieldset>
                    <fieldset class="form-group">
                        <label for="birthday">Date de naissance <span class="text-danger">*</span></label>
                        <input type="date" class="form-control" name="birthday" id="birthday" aria-describedby="birthdayText">
                        <small id="birthdayText" class="form-text text-muted">
                            Attention ! Vous devez être âgé d'au moins 14 ans pour vous inscrire.
                        </small>
                    </fieldset>
                    <fieldset class="form-group">
                        <label for="password">Mot de passe <span class="text-danger">*</span></label>
                        <input type="password" class="form-control" name="password" id="password" aria-describedby="passwordText">
                        <small id="passwordText" class="form-text text-muted">
                            Le mot de passe doit au moins contenir 8 caractères.
                        </small>
                    </fieldset>
                    <fieldset class="form-group">
                        <label for="confPassword">Confirmation du mot de passe <span class="text-danger">*</span></label>
                        <input type="password" class="form-control" name="confPassword" id="confPassword">
                        <div id="passwordController">
                            <span id="low"></span>
                            <span id="medium"></span>
                            <span id="strong"></span>
                            <p></p>
                        </div>
                    </fieldset>
                    <fieldset class="form-group text-center">
                        <button type="submit" class="btn btn-primary btn-block">S'inscrire</button>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/modals/log-modal.blade.php
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Connexion</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body p-3">
                <form id="logForm" action="{{ route('auth.login') }}" method="post">
                    @csrf
                    <fieldset class="form-group">
                        <label for="logEmail">Adresse e-mail</label>
                        <input type="email" class="form-control" name="logEmail" id="logEmail" placeholder="mon-email@exemple.fr">
                    </fieldset>
                    <fieldset class="form-group">
                        <label for="logPassword">Mot de passe</label>
                        <input type="password" class="form-control" name="logPassword" id="logPassword">
                    </fieldset>
                    <fieldset class="form-group text-center">
                        <button type="submit" class="btn btn-success btn-block">Se Connecter</button>
                    </fieldset>
                </form>
                <div class="row">
                    <div class="col text-right">
                        <a href="{{ route('user.reset.password.view') }}">Mot de passe oublié ?</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/modals/maps.blade.php
<div id="maps-modal" class="modals" style="display: none">
    <button type="button" class="close text-danger" id="close-modal">
        <i class="fas fa-times fa-2x"></i>
    </button>
    <iframe src="" frameborder="0"></iframe>
</div>

resources/views/modals/profile-modal.blade.php
<div class="modal fade" id="profileModal" tabindex="-1" role="dialog" aria-labelledby="profileModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Inscription</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body p-3">
                <p class="text-danger small text-right">
                    * Champs obligatoires
                </p>
                <form id="profileForm" action="{{ route('user.update') }}" method="post">
                    @csrf
                    @method('put')
                    @if(auth()->check())
                        <input type="hidden" id="user-id" name="user" value="{{ encrypt(auth()->user()->email) }}">
                    @endif
                    <fieldset class="form-group">
                        <label for="username">Pseudo Mincraft <span class="text-danger">*</span></label>
                        <input type="text" name="username" id="username" class="form-control" value="{{ auth()->user()->username }}">
                    </fieldset>
                    <fieldset class="form-group">
                        <label for="email">Adresse e-mail <span class="text-danger">*</span></label>
                        <input type="email" class="form-control" name="email" id="email" value="{{ auth()->user()->email }}">
                    </fieldset>
                    <fieldset class="form-group">
                        <label for="birthday">Date de naissance <span class="text-danger">*</span></label>
                        <input type="date" class="form-control" name="birthday" id="birthday" value="{{ auth()->user()->birthday }}">
                    </fieldset>
                    <fieldset class="form-group">
                        <label for="password">Mot de passe</label>
                        <input type="password" class="form-control" name="password" id="password" aria-describedby="passwordText">
                        <small id="passwordText" class="form-text text-muted">
                            Le mot de passe doit au moins contenir 8 caractères.
                        </small>
                    </fieldset>
                    <fieldset class="form-group">
                        <label for="confPassword">Confirmation du mot de passe</label>
                        <input type="password" class="form-control" name="confPassword" id="confPassword">
                        <div id="passwordController">
                            <span id="low"></span>
                            <span id="medium"></span>
                            <span id="strong"></span>
                            <p></p>
                        </div>
                    </fieldset>
                    <fieldset class="form-group text-center">
                        <button type="submit" class="btn btn-outline-primary btn-block btn-sm">Mettre à jour</button>
                    </fieldset>
                </form>
                <form action="{{ route('user.delete') }}" method="post">
                    @csrf
                    @method('delete')
                    <input type="hidden" name="user" value="{{ encrypt(auth()->id()) }}">
                    <fieldset class="form-group text-center">
                        <button type="submit" class="btn btn-outline-danger btn-block btn-sm">Supprimer le compte</button>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>