routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// AUTH ROUTES
Route::prefix('/auth')->name('auth.')->group(function ()
{
    $auth = "AuthController";

    Route::get('/logout', "$auth@logout")->name('logout')->middleware('auth');

    Route::post('/login', "$auth@login")->name('login');
});

// GUIDE ROUTES
Route::prefix('/guide')->name('guide.')->group(function ()
{
    $guide = "GuideController";

    Route::get('/', "$guide@home")->name('home');
    Route::get('/server-rules', "$guide@server_rules")->name('server-rules');
});

// HELPERS ROUTES
Route::prefix('/helpers')->name('helpers.')->group(function ()
{
    $helpers = 'HelpersController';

    Route::get('/profile/activation/{type?}', "$helpers@profile_activation")->name('profile.activation');

    Route::get('/profile/delete/{type?}', "$helpers@profile_delete")->name('profile.delete');

    Route::get('/email/activation', "$helpers@email_activation")->name('email.activation');

    Route::get('/reset-password', "$helpers@reset_password")->name('reset.password');
    Route::get('/reset-password/expire', "$helpers@reset_password_expire")->name('reset.password.expire');
    Route::get('/reset-password/end', "$helpers@reset_password_end")->name('reset.password.end');
});

// MAIN ROUTES
$main = "MainController";

Route::get('/', "$main@home")->name('home');
Route::get('/mentions-legales', "$main@mentions")->name('mentions');
Route::get('/download', "$main@download")->name('download');

Route::post('/contact/send', "$main@contact")->name('contact');

// USER ROUTES
Route::prefix('/user')->name('user.')->group(function ()
{
    $user = "UserController";

    Route::get('/profile/activation/{token}', "$user@activation")->name('activation');
    Route::get('/password-reset', "$user@password_reset")->name('reset.password.view');
    Route::get('/password-reset/{token}', "$user@password_reset_end")->name('reset.password.end');

    Route::post('/profile/inscription', "$user@inscription")->name('inscription');
    Route::post('/password-reset/send', "$user@password_reset")->name('reset.password');

    Route::put('/profile/update', "$user@update")->name('update');
    Route::put('/password/update', "$user@password_reset")->name('reset.password.update');

    Route::match(['get', 'delete'], '/profile/delete/{token?}', "$user@delete")->name('delete');
});

resources/views/layouts/base.blade.php
<!doctype html>
<html lang="fr">
    <head>
        <!-- meta -->
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- title -->
        <title>@yield('title') | Aventure-Craft, Serveur Minecraft MMORPG</title>

        <!-- favicon -->
        <link rel="shortcut icon" href="{{ asset('images/favicon.png') }}" type="image/x-icon">

        <!-- stylesheet -->
        <link rel="stylesheet" href="{{ asset('css/main.css') }}">
        <link rel="stylesheet" href="{{ asset('fontawesome/css/all.min.css') }}">

        <!-- jquery 3.3.1 -->
        <script src="{{ asset('js/helpers/jquery-3.3.1.min.js') }}"></script>
        <!-- parallax js -->
        <script src="{{ asset('js/helpers/parallax.min.js') }}"></script>
    </head>
    <body>
        <!-- Header -->
        <header id="page-header" class="parallax-window" data-parallax="scroll" data-image-src="{{ asset('images/bg-header.jpg') }}">
            <nav id="menu" class="navbar navbar-expand-lg navbar-dark bg-brown fixed-top pt-2 pb-2 p-lg-0">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="container">
                    <div class="collapse navbar-collapse d-lg-flex justify-content-between" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('home') }}">Accueil</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('guide.home') }}">Guide</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('guide.server-rules') }}">Nos Règles</a>
                            </li>
                        </ul>
                        <div class="text-white">
                            Adresse serveur : <em>Aventure.craft.vg:25565</em>
                        </div>
                        <div>
                            @if(auth()->check())
                                <button type="button" class="btn btn-outline-warning mr-2" data-toggle="modal" data-target="#profileModal">Mon Compte</button>
                                <a href="{{ route('auth.logout') }}" class="btn btn-outline-danger">Déconnexion</a>
                            @else
                                <button type="button" class="btn btn-success mr-2" data-toggle="modal" data-target="#loginModal">Connexion</button>
                                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#inscriptModal">Inscription</button>
                            @endif
                        </div>
                    </div>
                </div>
            </nav>
            <div id="logo-title">
                <a href="{{ route('home') }}">
                    <img src="{{ asset('images/logo-title.png') }}" alt="logo-title">
                </a>
            </div>
        </header>
        <!-- End header -->

        <div class="container  mt-md-4 mb-4">
            <div class="row">
                <!-- Main -->
                <main class="col-12 col-md-9">
                    @yield('main')
                </main>
                <!-- End main -->
                <!-- Aside -->
                <aside class="d-none d-md-block col-md-3">
                    @yield('aside')
                    <section class="bg-white p-2 mb-4">
                        <a href="{{ route('download') }}"><img src="{{ asset('images/slider-jouer.png') }}" alt="slider-jouer"></a>
                    </section>
                    @if(auth()->check())
                    <section class="bg-white p-2 mb-4">
                        <!--<div class="row">
                            <div class="col">
                                <iframe id="mini-maps" class="w-100" height="300" src="http://www.averall.aventure-craft.com" frameborder="0" referrerpolicy="no-referrer-when-downgrade"></iframe>
                            </div>
                        </div>-->
                        <div class="row">
                            <div class="col">
                                <a id="maps-button" href="http://www.averall.aventure-craft.com" data-img="{{ asset('images') }}" target="_blank">
                                    <img src="{{ asset('images/map-off.png') }}" alt="map">
                                </a>
                            </div>
                        </div>
                    </section>
                    @endif
                    <section class="bg-white p-2 text-center">
                        <h5>Retrouvez-nous sur :</h5>
                        <div class="d-flex justify-content-around w-75 m-auto">
                            <a href="https://www.facebook.com/aventurecraftfr" target="_blank">
                                <i class="fab fa-facebook-square fa-2x" style="color: #3b5998;"></i>
                            </a>
                            <a href="https://twitter.com/AventureCraft_" target="_blank">
                                <i class="fab fa-twitter-square fa-2x" style="color: #33ccff;"></i>
                            </a>
                            <a href="https://discord.gg/QtjNDk9" target="_blank">
                                <i class="fab fa-discord fa-2x" style="color: #7289da;"></i>
                            </a>
                            <a href="https://www.youtube.com/user/easycraftyt" target="_blank">
                                <i class="fab fa-youtube fa-2x" style="color: #ff0000;"></i>
                            </a>
                        </div>
                    </section>
                    @if (auth()->check())
                    <section class="text-center mt-4">
                        <button class="btn btn-warning btn-block" data-toggle="modal"
                                data-target="#contactModal">
                            <strong>Nous contacter</strong>
                        </button>
                    </section>
                    @endif
                </aside>
                <!-- End aside -->
            </div>
        </div>

        <!-- Footer -->
        <footer class="text-center text-white">
            <p>Aventure-Craft&copy;2019 - Tous droits réservés - <a href="{{ route('mentions') }}">Mentions
                    légales</a></p>
        </footer>
        <!-- End footer -->

        <!-- Modals -->
        @include('modals.contact-modal')
        @if(auth()->check())
            @include('modals.profile-modal')
            @include('modals.maps')
        @else
            @include('modals.log-modal')
            @include('modals.inscript-modal')
        @endif
        <!-- End modals -->

        <!-- js script -->
        <script src="{{ asset('js/helpers/bootstrap.min.js') }}"></script>
        <script src="{{ asset('js/helpers/popper.min.js') }}"></script>
        <script src="{{ asset('js/dist/app.js') }}"></script>
        @yield('script')
    </body>
</html>

resources/views/layouts/guide.blade.php
@extends('layouts.base')

@section('title', "Le Guide")

@section('aside')
    <nav class="nav flex-column mb-4">
        <a href="{{ route('guide.home') }}" class="nav-link">Accueil</a>
        <a href="{{ route('guide.server-rules') }}" class="nav-link">Nos règles</a>
    </nav>
@endsection

resources/views/layouts/helpers.blade.php
@extends('layouts.main')

@section('script')
    <script>
        window.scrollTo(0, 500);

        let start = 10;
        let i = 0;
        let chrono_content = $('#chrono');

        $chrono = setInterval(function ()
        {
            $('#chrono').text(start - i);
            i++;
            if (i >= start)
                window.location.href = $('#message').data('route');
        }, 1000);
    </script>
@endsection

@section('main')
    <section id="message" class="row bg-white" data-route="{{ route('home') }}">
        <div class="col p-4">
            @yield('content')
            <hr>
            <p>Si vous avez des problème avec le site, contactez-nous !</p>
            <p>Vous allez être redirigé vers la page d'accueil dans <span id="chrono" class="text-primary"></span>...</p>
        </div>
    </section>
@endsection

resources/views/layouts/mail.blade.php
<!doctype html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>@yield('title') | {{ config('app.name') }}</title>
    <body style="background-color: #333;font-family: 'sans-serif';">
        <table align="center" cellpadding="0" cellspacing="0" width="500" bgcolor="#fff">
            <tr>
                <td id="header" align="center" height="150">
                    <a href="{{ route('home') }}" target="_blank">
                        <img data-src="{{ asset('images/logo-title.png') }}" src="{{ asset('images/logo-title.png') }}" alt="bg-header" width="260">
                    </a>
                </td>
            </tr>
            @yield('content')
            <tr>
                <td align="center" height="50">
                    <small>
                        <a href="{{ route('home') }}" target="_blank">Aventure-Craft</a>&copy;2019-Tous droits réservés.
                    </small>
                </td>
            </tr>
        </table>
    </body>
</html>

resources/views/layouts/main.blade.php
@extends('layouts.base')